[variables]
PUPPETEER_SKIP_DOWNLOAD = "true"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_CACHE_DIR = "/tmp/puppeteer-cache"

[phases.setup]
nixPkgs = [
  "...",
  "chromium",
  "glib",
  "nss",
  "nspr",
  "atk",
  "cups",
  "dbus",
  "libxcb",
  "libxkbcommon",
  "pango",
  "cairo",
  "alsa-lib",
  "gtk3",
  "mesa",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXdamage",
  "xorg.libXext",
  "xorg.libXfixes",
  "xorg.libXrandr"
]
aptPkgs = [
  "libglib2.0-0",
  "libnss3",
  "libnspr4",
  "libatk1.0-0",
  "libatk-bridge2.0-0",
  "libcups2",
  "libdbus-1-3",
  "libdrm2",
  "libxcb1",
  "libxkbcommon0",
  "libx11-xcb1",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxrandr2",
  "libgbm1",
  "libpango-1.0-0",
  "libcairo2",
  "libasound2",
  "libgtk-3-0"
]

[phases.build]
cmds = ["npm install"]

[start]
cmd = "CHROME_PATH=$(which chromium || which chromium-browser || which google-chrome || true) PUPPETEER_EXECUTABLE_PATH=$(which chromium || which chromium-browser || which google-chrome || true) npm start"
